sonar.organization=dechrist
sonar.projectKey=DeChrist_blue-score
sonar.projectName=blue-score
sonar.projectVersion=0.1.0

sonar.sources=src
sonar.exclusions=**/*.test.ts,**/*.test.tsx
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/main.tsx,src/sampleData.ts
